main: com.andrei1058.ageofempire.Main
name: Age-Of-Empire
version: 1.2.7
author: andrei1058
description: AgeOfEmpire minigame.
website: http://andrei1058.com

commands:
  setup:
    description: Main setup command
    permission: aoe.setup
    aliases: [s]
  leave:
    description: Leave the game
    permission: aoe.leave
  help:
    description: Enable/Disable the guide
    aliases: [h]

permissions:
  aoe.setup:
    default: op
    description: Allows to use setup commands
  aoe.leave:
    default: true
    description: Allows to leave the game